# Generated by Django 3.1.3 on 2021-02-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210131_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
