# Generated by Django 3.1.3 on 2021-02-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_follow'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='post',
            order_with_respect_to='timestamp',
        ),
    ]
