# Generated by Django 3.1.3 on 2021-02-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210203_0234'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='post',
            order_with_respect_to=None,
        ),
    ]
