# Generated by Django 3.1.3 on 2021-02-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abduHR', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
